name       : ghostwriter
version    : 1.6.2
release    : 9
source     :
    - https://github.com/wereturtle/ghostwriter/archive/v1.6.2.tar.gz : fea5a1b2b2ebd79c2814ff32c4b9d3bdc983f8260566fc7a1c9795da592d97c0
license    : GPL-3.0
component  : editor
summary    : Cross-platform, aesthetic, distraction-free Markdown editor.
description: |
    ghostwriter is a Windows and Linux text editor for Markdown, ghostwriter provides a relaxing, distraction-free writing environment, whether your masterpiece be that next blog post, your school paper, or your NaNoWriMo novel.
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(librsvg-2.0)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
