name       : ghostwriter
version    : 2.1.2
release    : 19
source     :
    - https://github.com/wereturtle/ghostwriter/archive/refs/tags/2.1.2.tar.gz : 65aa523a9c3d4f4c68f2cb6f5ab600cf24c98b4f0673a622d757a8e28eab120f
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : editor
homepage   : https://wereturtle.github.io/ghostwriter/
summary    : Cross-platform, aesthetic, distraction-free Markdown editor.
description: |
    ghostwriter is a Windows and Linux text editor for Markdown, ghostwriter provides a relaxing, distraction-free writing environment, whether your masterpiece be that next blog post, your school paper, or your NaNoWriMo novel.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(hunspell)
    - pkgconfig(librsvg-2.0)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
