name       : ghostwriter
version    : 23.04.2
release    : 27
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/ghostwriter-23.04.2.tar.xz : db8b1c9370863a9596cd00e1dc230caf94cac01ad963e962820db58281efbdda
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : editor
homepage   : https://wereturtle.github.io/ghostwriter/
summary    : Cross-platform, aesthetic, distraction-free Markdown editor.
description: |
    ghostwriter is a Windows and Linux text editor for Markdown, ghostwriter provides a relaxing, distraction-free writing environment, whether your masterpiece be that next blog post, your school paper, or your NaNoWriMo novel.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(hunspell)
    - pkgconfig(librsvg-2.0)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kconfigwidgets-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
