name       : ghostwriter
version    : 1.7.4
release    : 13
source     :
    - https://github.com/wereturtle/ghostwriter/archive/v1.7.4.tar.gz : 4987126e71a37556e575fbce2002c5504cf15a04c11bcce604a278f59ec9c11a
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : editor
summary    : Cross-platform, aesthetic, distraction-free Markdown editor.
description: |
    ghostwriter is a Windows and Linux text editor for Markdown, ghostwriter provides a relaxing, distraction-free writing environment, whether your masterpiece be that next blog post, your school paper, or your NaNoWriMo novel.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(hunspell)
    - pkgconfig(librsvg-2.0)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
